# # TODO: Update Node, then this will auto-setup
# name: Gemer - Gem Version Tests
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#
#     - uses: actions/checkout@v2
#     - name: Ruby Gemer
#       uses: katungi/Ruby-Gemer@V0.1-alpha
