Metrics/BlockLength:
  Max: 56
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
