inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Lint/UselessAssignment:
  Exclude:
    - 'db/seeds.rb'

Metrics/BlockLength:
  Max: 56
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Rails/FilePath:
  Enabled: false

# Convention over configuration
Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 25

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'config/application.rb'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/update'

Style/StringLiterals:
  EnforcedStyle: double_quotes
