name: RSpec
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          RAILS_ENV: test
          POSTGRES_PASSWORD: password
          PG_HOST: /var/run/postgresql
          PG_USER: SoloAsana
          PG_PASSWORD: password
          PG_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - uses: actions/setup-node@v1
        with:
          node-version: '6.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Node dependencies
        run: npm install
      - uses: nanasess/setup-chromedriver@master
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run rspec
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DATABASE_URL: postgres://postgres:@localhost:5432/SoloAsana_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_PASSWORD: password
          PG_HOST: /var/run/postgresql
          PG_USER: SoloAsana
          PG_PASSWORD: password
          PG_PORT: 5432
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:setup
          bundle exec rspec
      - name: Test & publish code coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        uses: paambaati/codeclimate-action@v3.0.0
