# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run rspec
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Rspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5']

    services:
      postgres:
        image: postgres:9
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '6.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Gem cache
      id: cache-bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}

    - name: Bundle install
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Install yarn
      run: npm install -g yarn

    # NOTE: Yarn cache doesn't seem to be working quite yet
    - name: Get yarn cache dir
      id: yarn-cache-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Yarn cache
      id: cache-yarn
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Yarn install
      run: yarn install

    - name: Setup DB, Run tests
      env:
        PGHOST: SoloAsana_test
        PGUSER: SoloAsana
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        bin/rails db:create db:schema:load
        bundle exec rspec
    # - name: Set up Ruby
    # # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # # change this to (see https://github.com/ruby/setup-ruby#versioning):
    #   uses: ruby/setup-ruby@v1
    #   # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
    #   with:
    #     ruby-version: ${{ matrix.ruby-version }}
    #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    #
    #
    # - name: Setup Node
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 6.10.1
    # - name: Find yarn cache location
    #   id: yarn-cache
    #   run: echo "::set-output name=dir::$(yarn cache dir)"
    # - name: JS package cache
    #   uses: actions/cache@v1
    #   with:
    #     path: ${{ steps.yarn-cache.outputs.dir }}
    #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-yarn-
    # - name: Install packages
    #   run: |
    #     yarn install --pure-lockfile
    #
    # - name: Setup test database
    #   env:
    #     RAILS_ENV: test
    #   run: bin/setup
    #
    # - name: Run tests
    #   run: bundle exec rspec
